### ISSUE TITLE
Реальные исходники finance.ua?

### ISSUE THREAD

**Issue by Sharabaddin** [victron/finance_ua#1]
Добрый день. Это реальные исходники finance.ua?

**Comment by victron** [comment]
нет, никакого отношения к finance.ua не имеет

**Comment by Sharabaddin** [comment]
а что за проект?

**Comment by victron** [comment]
обычная домашняя игрушка. Сбор предложений продажи/покупки валюты из разных источников, + сбор некоторой статистики. Частичное отображение. Анализа пока не планирую.

**Comment by Sharabaddin** [comment]
Прикольно вобще.  А я хочу сделать нечто подобное с последующим анализом. А кокретннно получением и  долара на межбанке и по комерчиским банкам с последующим анализом. И прогнозированием на основе анализа статистики)
